### ISSUE TITLE
Multiple-select break google maps

### ISSUE THREAD

**Issue by itajackass** [wenzhixin/multiple-select#483]
If I use mutiple-select in a page with google maps:

`<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=xxxxxxxxxxxxx"></script>`

My maps doesn't show.

Console error:

TypeError: can't convert Symbol.iterator to string: its [Symbol.toPrimitive] method returned an object

The problem occur with 1.4.1 version.
No problem with 1.4.0

**Comment by wenzhixin** [comment]
Fixed in #474, please confirm this problem with the next version.

**Comment by itajackass** [comment]
I just downloaded new version 1.4.2 now, but the problem still remain:

CHROME CONSOLE LOG:

Uncaught (in promise) TypeError: Cannot convert object to primitive value
    at Object._.Ca (js?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:26)
    at df.cf [as i] (js?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:76)
    at ef (js?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:76)
    at js?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:77
    at lf (js?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:78)
    at mf (js?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:77)
    at js?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:77
    at lf (js?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:78)
    at mf (js?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:77)
    at js?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:77


FIREFOX LOG:

TypeError: can't convert Symbol.iterator to string: its [Symbol.toPrimitive] method returned an object

**Comment by wenzhixin** [comment]
Sorry, next version 1.4.3

**Comment by wenzhixin** [comment]
@itajackass 1.4.3 released now.

**Comment by itajackass** [comment]
Thank you. bug solved!
